### ISSUE TITLE
makeSelBox() is deprecated since 2.5.9

### ISSUE THREAD

**Issue by cesagonchu** [GregMage/TDMDownloads#2]
Quand je vais pour créer une catégorie, le mode debug m'affiche cette erreur :

Notice: makeSelBox() is deprecated since 2.5.9, please use makeSelectElement(), accessed from /modules/TDMDownloads/class/tdmdownloads_cat.php line 104, in file /class/tree.php line 217

___
Ma config :

PHP: 7.0.13-0ubuntu0.16.10.1
MYSQL: 5.7.17-0ubuntu0.16.10.1
XOOPS: 2.5.9-Beta1 version anglaise
Module TDMDownloads 1.65 RC 1 (téléchargé ce jour, le 31 Janvier 2017)

**Comment by GregMage** [comment]
Salut,

Merci pour ton retour! C'est normal pour le moment, j'ai pas modifié pour rester compatible avec 2.5.8. Mais comme une autre partie du code n'est pas compatible avec 2.5.8, j'hésite à sortir une version compatible 2.5.8 en corrigeant ce bout de code ou de corriger cet avertissement pour être compatible uniquement 2.5.9. Tu en penses quoi?

**Comment by cesagonchu** [comment]
J'en pense que côté FR on n'aura jamais de 2.5.8, mais une 2.5.9. Donc, autant désigner ton module comme compatible avec 2.5.9 uniquement. Elle va bientôt sortir d'ailleurs ;-)
Après, c'est toi le chef ! :-P

**Comment by GregMage** [comment]
Merci pour ta réponse, je fais ce que tu me conseil. La version 1.65 finale est donc ok et j'ai corrigé la bug.

**Comment by cesagonchu** [comment]
Merci ! 👍 
Par contre je n'ai pas encore fini de tester alors s'il te plaît ne l'annonce pas encore :-)

**Comment by GregMage** [comment]
J'annonce rien mais normalement tout devrait fonctionner. Il n'y a pas beaucoup de modifications par rapport à l’ancienne version.

**Comment by cesagonchu** [comment]
Il y a aussi Heyula qui te prépare un thème pour le module, non ?
http://xoops.org/modules/newbb/viewtopic.php?post_id=362021#362021

**Comment by GregMage** [comment]
Je sais pas, c'est pas très clair... Dans tout les cas, les améliorations c'est pour la version 1.66. Je ne veux pas tout mélanger. La version 1.65 c'est uniquement la compatibilité avec 2.5.9.
