### ISSUE TITLE
Not working with Latest Tag Module

### ISSUE THREAD

**Issue by liomj** [GregMage/TDMDownloads#5]
when we use tag module the submit page is not working

xoopsFormtag is deprecated use tagFormtag

disabling the tag in Preferences the module works fine

https://github.com/xoopsmodules25x/tag/

**Comment by cesagonchu** [comment]
Why don't you put the issue at the right place?
[https://github.com/xoopsmodules25x/tag/](https://github.com/xoopsmodules25x/tag/)

**Comment by liomj** [comment]
theres a changelog in the tag module

**deprecated XoopsFormTag (modules should not create classes beginning with  'Xoops'). 
Created class TagFormTag to replace it. (zyspec)**

if im not mistaken i believe xoopsFormtag is still used in tdmdownloads

**Comment by GregMage** [comment]
No problem of this type with TDMDowloads. There was a display problem but it was fixed!

https://github.com/GregMage/TDMDownloads/commit/ea31a3e60c9ba56f6ed5c3a675dc90801b11ed5a

**Comment by GregMage** [comment]
> deprecated XoopsFormTag (modules should not create classes beginning with 'Xoops').
Created class TagFormTag to replace it. (zyspec)

Fixed

https://github.com/GregMage/TDMDownloads/commit/52ff7b4f85d129cf4fa1950d29c7cdbf7e8d541d
